### PR TITLE
Vim: Initial integration of TextLint in quickfix window

### PR DESCRIPTION
**Pull request by cdlm**
I'm working on a nicer version, but this works fine.

To use it in Vim, the best is to use something like [pathogen](https://github.com/tpope/vim-pathogen) and checkout the textlint repo in `~/.vim/bundle`. Then invoke `:TextLint` from your text buffer. This uses Vim's `quickfix` feature, with the standard `:cn` commands to navigate between errors.

### CODE REVIEW

**Comment by DamienCassou** [comment]
Please add necessary changes to README.markdown and I will integrate. Thank you very much.

**Comment by DamienCassou** [comment]
Integrated everything but commit #6d37a1a which is work in progress.

**Comment by renggli** [comment]
Damien Cassou do you merge that?

On 27 September 2011 17:58, Damien Pollet
reply@reply.github.com
wrote:

> I'm working on a nicer version, but this works fine.
> 
> To use it in Vim, the best is to use something like [pathogen](https://github.com/tpope/vim-pathogen) and checkout the textlint repo in `~/.vim/bundle`. Then invoke `:TextLint` from your text buffer. This uses Vim's `quickfix` feature, with the standard `:cn` commands to navigate between errors.
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/cdlm/textlint vim-support
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/DamienCassou/textlint/pull/13
> 
> -- Commit Summary --
> - Vim: Initial integration of TextLint in quickfix window
> 
> -- File Changes --
> 
> A plugin/textlint.vim (47)
> 
> -- Patch Links --
> 
>  https://github.com/DamienCassou/textlint/pull/13.patch
>  https://github.com/DamienCassou/textlint/pull/13.diff
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DamienCassou/textlint/pull/13

## 

Lukas Renggli
www.lukas-renggli.ch

**Comment by cdlm** [comment]
On 29 September 2011 16:06, Lukas Renggli
reply@reply.github.com
wrote:

> Damien Cassou do you merge that?

he merged it already.

## 

Damien Pollet
type less, do more [ | ] http://people.untyped.org/damien.pollet

**Comment by dwcoder** [comment]
cdlm

I found that the quickfix integration no longer works, but I added a comment in the textlint.vim file with a possible fix (that worked on my system at least).

**Pull request closed without merging**
